executable="${CDT_HOME}/cdt"

[alias]
initcs="moab init csharp"
initj="moab init java"
initgo="moab init java sdk/sdk-golang"
cproj = "!checkout-projects.sh \"$@\""
co="moab checkout"
hooks="!install-hooks.sh"
jira="!add-jira-prefix.sh"
ide="moab ide"
rmoab="moab refresh"
st="moab status"
